global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: "8062542410:AAGUoQdj9bUqPS51bGk2dUJcAAAyw4wvVdI"
        chat_id: -1001618404393
        parse_mode: HTML
        message: |
          ðŸš¨ <b>{{ .CommonAnnotations.summary }}</b>
          
          {{ range .Alerts }}
          ðŸ”¹ {{ .Annotations.description }}
          ðŸ”¹ Status: {{ .Status }}
          ðŸ”¹ StartsAt: {{ .StartsAt }}
          {{ end }}
