global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'dance-cup-api'
    static_configs:
      - targets: ['dance-cup-api:81', 'dance-cup-api-2:81', 'dance-cup-api-3:81']
        labels:
          service: 'dance-cup-api'

  - job_name: 'dance-cup-auth'
    static_configs:
      - targets: ['dance-cup-auth:81']
        labels:
          service: 'dance-cup-auth'
          
  - job_name: 'dance-cup-ui'
    static_configs:
      - targets: ['host.docker.internal:5215']
        labels:
          service: 'dance-cup-ui'

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093